### PR TITLE
Add myself as a member of DevOps SIG

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
As [Roles.md#member](https://github.com/kubesphere/community/blob/master/ROLES.md#member) mentioned, you need to have notable contribution to the project to become a member of KubeSphere community. This PR will be merged in the proper time, keep going.

**Comment by LinuxSuRen** [comment]
@FeynmanZhou Thanks for the remind.

**Comment by rayzhou2017** [comment]
Welcome @LinuxSuRen to join us!

**Review by rayzhou2017 — APPROVED** [review]
/lgtm

**Pull request merged**
