### PR TITLE
Add code review guide doc, pr author guide and coding conventions

### PR DESCRIPTION
**Pull request by zryfish**
Add code review and coding conventions guide.

`code-review-guide.md` are best practices from [Google Engineering Practices](https://google.github.io/eng-practices/), which would help us establish some code review standards.
`the-pr-author-guide-to-getting-through-code-review.md` from Google will help our contributors to create PRs of good quality. 
`coding-conventions.md` are some highlights from the Kubernetes community

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Comment by zryfish** [comment]
We are going to include this doc in `KubeSphere` PR templates, and maybe could let Prow comment PR with code-review doc link.

**Pull request merged**
