### PR TITLE
Reviewed expose-loadbalancer-services-using-iptables-nat-rules-en.

### PR DESCRIPTION
**Pull request by Patrick-LuoYu**
Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
/assign @wanjunlei @benjaminhuo @duanjiong @zheng1 @FeynmanZhou

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
I don't understand where are the conflicts come from?

**Comment by Patrick-LuoYu** [comment]
README.md was edited in two PRs. Everything should be fine in this PR.

**Comment by LinuxSuRen** [comment]
I didn't see any conflicts from the repo. I can see you already closed #306. Please rewrite your PR title here, make it be reasonable.

**Comment by Patrick-LuoYu** [comment]
Changed the PR title.

**Review by FeynmanZhou — APPROVED** [review]

**Pull request merged**
