### PR TITLE
Request to add faweizhao26 and yangchuansheng as the root owner

### PR DESCRIPTION
**Pull request by faweizhao26**
Signed-off-by: faweizhao26 <faweizhao@kubesphere.io>

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
It would be better if you could provide some background or context about the changes. Other contributors have no way to know why to do this. I don't know at least.

**Comment by faweizhao26** [comment]
@faweizhao26  and @yangchuansheng  are all the members of [Advocacy and Outreach Special Interest Group](https://github.com/kubesphere/community/tree/master/sig-advocacy-and-outreach). They are also very active.

So, They can help to maintain this repo. 

In addition，faweizhao26 is the administrator of ospp-2022. It will help him manage the projects if he is the root owner.

**Comment by LinuxSuRen** [comment]
> In addition，faweizhao26 is the administrator of ospp-2022. It will help him manage the projects if he is the root owner.

In this case, having approval permission of `sig-advocacy-and-outreach` is good enough.

**Pull request closed without merging**
