### PR TITLE
add the writer info of deploy harbor

### PR DESCRIPTION
**Pull request by spwangxp**
Signed-off-by: shengpengwang <shengpengwang@yunify.com>

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@spwangxp Please fix the conflicts first. BTW, I remember everyone may need to claim 3 tasks from this list.

**Comment by spwangxp** [comment]
confilct resolved, I will try my best to write more blog later.

**Review by rayzhou2017 — APPROVED** [review]
/lgtm

**Comment by rayzhou2017** [comment]
@spwangxp It seems you miss the sign off

**Pull request merged**
